@jtwToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X2lkIjowLCJleHAiOjE2MTU5NTQyMzMsImlkIjozNiwibmFtZSI6IkVnYSIsInJvbGUiOiJhZG1pbiIsInVzZXJuYW1lIjoiZWdhIn0.Afnmz1NNnTDD4qePK_VE9b_RHQGG2CgTSyhLORCmSO8
###
POST http://127.0.0.1:8585/api/account/bank
content-type: application/json
Authorization: Bearer {{jtwToken}}

{
    "Internal": false,
    "BankName": "BRI",
    "BankNumber":"898911111",
    "BankHolderName":"Tokopedia"
}
###
POST http://127.0.0.1:8585/api/account/financial
content-type: application/json
Authorization: Bearer {{jtwToken}}

{
    "Name": "Interest",
    "AccountType":"INCOME"
}

###

GET http://127.0.0.1:8585/api/account/100
Authorization: Bearer {{jtwToken}}
###
POST http://127.0.0.1:8585/api/transaction/
content-type: application/json
Authorization: Bearer {{jtwToken}}
{
    "AccountID": 32,
    "Amount": -100000,
    "Remarks": "Kurangin dong"
}

###
GET http://127.0.0.1:8585/api/projects/financial/29
###
GET http://127.0.0.1:8585/api/projects/1

###
GET http://127.0.0.1:8585/api/projects?range=[0,10]
Authorization: Bearer {{jtwToken}}
###
POST http://127.0.0.1:8585/api/projects
content-type: application/json
Authorization: Bearer {{jtwToken}}

{
    "Name": "SDF Ke5",
    "TotalBudget": 50000000,
    "Description":"Psadsad"
}
###
GET http://127.0.0.1:8585/api/transactions?filter={"projectIDs":[]}
###
POST http://127.0.0.1:8585/api/projects/transaction
content-type: application/json
Authorization: Bearer {{jtwToken}}

{
    "ProjectID": 35,
    "Amount":6500,
    "Remarks":"biaya admin sdf bayar ke toped",
    "TransactionDate":"2021-03-14T00:10:50+00:00",
    "Notes":"",
    "Meta":"",
    "SourceProjectAccountID":90,
    "DestProjectAccountID":96,
    "SourceBankAccountID":101,
    "DestBankAccountID":102
}

###
POST http://127.0.0.1:8585/api/projects/pocket
content-type: application/json

{
    "ProjectID": 2,
    "Budget": null,
    "Name":"Firmawre"
}

###
POST http://127.0.0.1:8585/api/projects/transfer
content-type: application/json

{
   "ProjectIDSource": 1,
    "BudgetIDSource": 6,
    "ProjectIDTarget": 1,
    "BudgetIDTarget": 7,
    
    "Amount":11000,
    "Remarks":"inner project trf"
}


###

GET http://127.0.0.1:8585/api/users?range=[0,100]

###
POST http://127.0.0.1:8585/api/users
Content-Type: application/json
Authorization: Bearer {{jtwToken}}

{
    "Fullname": "Ega",
    "Username": "ega",
    "Password":"egabambang",
    "Email":"ega@ega.com",
    "Role":"admin"
}


###

DELETE http://127.0.0.1:8585/api/users/9
###
GET http://127.0.0.1:8585/api/payrec?range=[0,100]
###
POST http://127.0.0.1:8585/api/auth/login
content-type: application/json

{
    "Username": "ega",
    "Password": "egabambang"
}

###
GET http://localhost:8585/api/auth/test