POST http://127.0.0.1:8585/api/account/
content-type: application/json

{
    "Name": "PROJECT-FTW-FIRMWARE",
    "ParentAccount": 14
}

###
GET http://127.0.0.1:8585/api/account?limit=5&offset=4
###

GET http://127.0.0.1:8585/api/account/33

###
POST http://127.0.0.1:8585/api/transaction/
content-type: application/json

{
    "AccountID": 32,
    "Amount": -100000,
    "Remarks": "Kurangin dong"
}

###
GET http://127.0.0.1:8585/api/projects/1

###
GET http://127.0.0.1:8585/api/projects?range=[0,10]

###
POST http://127.0.0.1:8585/api/projects
content-type: application/json

{
    "Name": "SDF Kedua",
    "TotalBudget": 50000000,
    "Description":"Psadsad",
    "Budgets":[
        {
            "Name":"Mechanical",
            "Budget":null
        },
        {
            "Name":"Electrical",
            "Budget":1000000
        }
    ]
}
###
GET http://127.0.0.1:8585/api/transactions?filter={"projectIDs":[]}
###
POST http://127.0.0.1:8585/api/projects/transactions
content-type: application/json

{
    "ProjectID": 1,
    "BudgetID": null,
    "Amount":11000,
    "Remarks":"Halo"
}

###
POST http://127.0.0.1:8585/api/projects/pocket
content-type: application/json

{
    "ProjectID": 2,
    "Budget": null,
    "Name":"Firmawre"
}

###
POST http://127.0.0.1:8585/api/projects/transfer
content-type: application/json

{
   "ProjectIDSource": 1,
    "BudgetIDSource": 6,
    "ProjectIDTarget": 1,
    "BudgetIDTarget": 7,
    
    "Amount":11000,
    "Remarks":"inner project trf"
}


###

GET http://127.0.0.1:8585/api/users?range=[0,100]

###
POST http://127.0.0.1:8585/api/users
content-type: application/json

{
    "Fullname": "Bambang2",
    "Username": "bambang_22",
    "Password":"firmawafasfasfasfe",
    "Email":"bambangf@joko.kom",
    "Role":"admin"
}


###

DELETE http://127.0.0.1:8585/api/users/9
###
GET http://127.0.0.1:8585/api/payrec?range=[0,100]
###
POST http://127.0.0.1:8585/api/auth/login
content-type: application/json

{
    "Username": "ahmad",
    "Password": "Akuinginpintar24"
}