GET http://localhost:9090/transaction/1

###
POST http://localhost:9090/transaction
content-type: application/json

{
  "project_id": 1,
  "creator_id": 1,
  "category_id": 1,
  "paid": true,
  "sof_type": "user",
  "sof_user_id": 1,
  "sof_account": "",
  "paid_on": null,
  "description": "Makan makan",
  "amount": 10000,
  "type": "credit",
  "approved": true
}